:sparkles: Destroy nested copies
ct-js/ct-js-old pull request #127
Opened 2019-10-02 00:17 UTC by schadocalex

**Changes proposed in this pull request:**
- When a copy is destroyed, all its children are destroyed too.

Question : 
- What does `ct.types.onDestroy.apply(ct.stack[i]);` do?

**Ping @CosmoMyzrailGorynych**

2019-10-02 03:07 UTC, CosmoMyzrailGorynych commented
> What does ct.types.onDestroy.apply(ct.stack[i]); do?

All the `ct.types.on*` methods are populated by modules through injects, and thus these include logic common to all copies' types.

2019-10-02 04:04 UTC, CosmoMyzrailGorynych requested changes

2019-10-02 04:04 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    };
Don't make functions inside a loop

2019-10-02 04:04 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    ct.stack = ct.stack.filter(copy => !copy.kill);
I don't think it is better than a `for` loop.

* You create a new array and make all possible links to ct.stack. If one writes `this.roomCopies = ct.stack;`, their variable becomes invalid and causes a memory leak because of holding killed copies.
* A new array makes the old one a target for garbage collection. Can be relevant for tons of copies in a room.
* Performance of `.filter` should be measured.

2019-10-02 04:04 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +        ct.types.list[i] = ct.types.list[i].filter(type => !type.kill);
The same issue as with `ct.stack`, and it is more likely that developers will store a ref to a collection of a specific type somewhere. This is another trap laid for users.

2019-10-02 08:38 UTC, schadocalex commented on app/data/ct.release/main.js
> +    };
yes

2019-10-02 09:16 UTC, schadocalex commented on app/data/ct.release/main.js
> +    ct.stack = ct.stack.filter(copy => !copy.kill);
I answer here for the two comments about filter.

You got the point, I thought that : 
- ct.stack wan only used internally.
- if used externally, as ct.stask is global it might not be stored. But we can't know what devs do, so you're right.

So I will put splice back.

`filter` is a lot faster than splice, beacause splice is extremely slow if you don't have to remove only one element. I found a jsperf to show you : https://jsperf.com/splice-vs-filter If you have tons of object in a scene and want to delete half of them, it will be very slow.

The best structure to store objets like copies is `Set` for me. You add/delete instantly. But it is a breaking change if devs uses ct.stack directly.

Another alternative is to filter in place : https://stackoverflow.com/questions/37318808/what-is-the-in-place-alternative-to-array-prototype-filter (we can do it while looping over the array). But _maybe_ for only one element to remove it's slower than one native splice. If you want to try this solution tell me, else I keep the splice.

2019-10-02 10:13 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    ct.stack = ct.stack.filter(copy => !copy.kill);
I found this question as well, and either I screwed up with the tests badly or this approach is even faster than `Array.prototype.filter` (and `push`) by abt 5%: https://jsperf.com/splice-vs-filter/24

I modified the starting array so that it has 100 items from 0 to 99 and changed the filter's clause so it leaves 31 item in the array.

2019-10-02 10:35 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    ct.stack = ct.stack.filter(copy => !copy.kill);
Regarding the use of `Set`s, I'm looking positively towards them. It is indeed a breaking change, but for a really small portion of devs (if any).

What's more important is that the collections don't get replaced by new ones. E.g. here is a realistic example of why it matters:

```js
// Scenario "Pacman eats a bonus"

if (ct.place.occupied(this, bonus)) {
    const ghosts = ct.types.list['AngryGhosts']; // because otherwise lines get too long
    for (const ghost of ghosts) {
        ghost.scared = true;
    }
    ct.u.wait(1000 * 10) // an asynchronous task walks in
    .then(() =>
        for (const ghost of ghosts) {
            ghost.scared = false;
        }
    });
}
```

* if a ghost is deleted when waiting for 10s, it will stay in the old reference, eating memory and adding useless workload;
* if new ghosts were added and "scared" on creation, they won't get "unscared" later.

It is ofc not an example of perfect coding, but who ever codes flawlessly? Making such things reliable is important for inclusivity.

2019-10-02 11:27 UTC, schadocalex commented on app/data/ct.release/main.js
> +    ct.stack = ct.stack.filter(copy => !copy.kill);
You example is ok for me. But you could also store a subset of ghost if there is a asynchronous task for each (10s scared but not all synchronized), in that case the old reference is still there (but we can't do better with this pattern).

The only problem of Set is that it can be difficult for devs who never manipulate them (size instead of length, no map/filter method). So you have to be sure you want to force devs to use that.
In the other side it ensures a copy is never twice in the Set (don't know in which case it could happen).

So you might want to change all copies and types array by `Set`s? Or only copies?

2019-10-02 11:50 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    ct.stack = ct.stack.filter(copy => !copy.kill);
* inconsistencies in between similar things are bad, so either `Set`s everywhere or arrays;
* `Set`s are simple and cool but require a decent knowledge of iterators and programming high-order functions (e.g. how to make a function to filter/reduce/map a set).
   * => sets are bad

And so I choose arrays. I think it's my final decision 😄

2019-10-03 23:23 UTC, CosmoMyzrailGorynych commented
It throws an error when a parent is deleted :/ Children can be deleted safely.
![изображение](https://user-images.githubusercontent.com/3174357/66170637-164c6180-e699-11e9-9265-1f782ef2cd89.png)

I made a number of tiny test cases, it might help to debug:
[n127.zip](https://github.com/ct-js/ct-js/files/3688411/n127.zip)

2019-10-04 01:10 UTC, schadocalex commented
Thanks for the test cases! The last one was broken, I have repared it: [n127.zip](https://github.com/ct-js/ct-js/files/3688591/n127.zip)

I use a totally different approch for killing: I let pixi kill children and just check after for killed copies.

2019-10-04 02:33 UTC, CosmoMyzrailGorynych commented
Well, yes, I began to confuse the first and second container and mixed up the indices :sweat_smile: 

But I've found another bug ¯\_(ツ)_/¯ It is dependant on the creation order (more precisely on the position of a copy in the `stack`). See `Test_KillTwo` and `Test_KillTwo_reverse` rooms.

[n127.zip](https://github.com/ct-js/ct-js/files/3688737/n127.zip)

I suspect it is because pixi freaks out when one tries to destroy an already destroyed `DisplayObject`. Idk why pixi doesn't use its own variable to catch these, but a check for `copy._destroyed` may be enough.

2019-10-06 03:04 UTC, CosmoMyzrailGorynych approved these changes
:tada:

2019-10-06 03:06 UTC, merged