added the ability to import modules
ct-js/ct-js-old pull request #142
Opened 2019-11-01 04:03 UTC by leedigital

added the ability to import modules

2019-11-05 04:23 UTC, CosmoMyzrailGorynych requested changes

2019-11-05 04:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +            e.target.value = "";
ct.js uses single quotes in scripts

2019-11-05 04:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                    fileName.endsWith("module.json")) {
The second check is excess as ct.js looks for exactly `module.json`

2019-11-05 04:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                                entry.path = `${moduleName}${filePath.substring(indexOf)}`;
Please don't use this when working with paths in a file system. It will produce tons of unobvious errors on Windows.
Better use `path.join`, e.g. here `path.join(moduleName, ???)` — I don't get the meaning of `filePath.substring` here. If it is for getting the base name, it will fail with files in nested directories. A better solution is to use `path.basename(filePath)` ([docs](https://nodejs.org/api/path.html#path_path_basename_path_ext)).

2019-11-05 04:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                    moduleName = json.main.name;
`name` is more a readable, human-friendly name than an identifier like in npm packages. We could add a new parameter, though, — `main.packageName` — and default to the name of a zip file if this key was not found.

2019-11-05 14:48 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +            e.target.value = "";
okay... :-)

2019-11-05 14:55 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                    fileName.endsWith("module.json")) {
The second check is in case the module.json is under a parent directory, for example gamepad/module.json, and in this case this is necessary, because the file path comes with the name of the parent directory that contains it ... To remove this second check, I have to extract the module.json from the path. Do you want me to extract the module from the path?

2019-11-05 15:04 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                                entry.path = `${moduleName}${filePath.substring(indexOf)}`;
In this case, the module has a parent directory when it is zipped ... so I'm replacing it with the module name I get from the mdoule.json file. understood?

2019-11-05 15:10 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                    moduleName = json.main.name;
In this case, we can standardize things ... if the module is zipped under a parent directory, then I use that directory itself, otherwise use the zip filename to create a parent directory. what do you think?

2019-11-05 21:00 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                    fileName.endsWith("module.json")) {
Ah, I see. But yeah, it is better to compare to `path.basename(fileName);`

2019-11-05 21:01 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                                entry.path = `${moduleName}${filePath.substring(indexOf)}`;
Yep

2019-11-05 21:18 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                    moduleName = json.main.name;
Still, modules _should_ have an ID in their `package.json`: it will help building better infrastructure in the future (a la npm). Aaaaand I would not trust archivers :D So let's add `main.packageName` to modules' spec, and fallback to a subdirectory name, and then to a `.zip` file's name.

2019-11-05 22:39 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                    fileName.endsWith("module.json")) {
okay... ^_^

2019-11-05 22:44 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                    moduleName = json.main.name;
okay ... so I'll change the code based on this new structure ... if `main.packageName `exists, then use it ... otherwise use the zip filename.

2019-11-06 13:50 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                    fileName.endsWith("module.json")) {
Wouldn't it be better to use the path.posix or path.win32 object?
 [see](https://nodejs.org/api/path.html#path_windows_vs_posix)

2019-11-06 21:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/modules-panel.tag
> +                    fileName.endsWith("module.json")) {
No, it won't. Using one or another will force `path` to use delimiters for a specific OS while breaking stuff on another. Plain `path.*` methods detect OS automatically and handle paths according to the host system — and that's why using them is necessary.

2019-11-06 23:58 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                                entry.path = `${moduleName}${filePath.substring(indexOf)}`;
done

2019-11-06 23:58 UTC, leedigital commented on src/riotTags/modules-panel.tag
> +                    moduleName = json.main.name;
Done.

2019-11-07 01:15 UTC, CosmoMyzrailGorynych approved these changes
:tada:

2019-11-07 01:17 UTC, merged