Show/Hide the mouse cursor
ct-js/ct-js-old pull request #143
Opened 2019-11-05 12:21 UTC by Wend1go

Adds functions to show and hide the mouse cursor to the mouse catmod.

Should I also update the CHANGELOG.md?
What is the versioning scheme for catmods: **CompleteRewrite** **.** **NewFeature** **.** **BugFix** ?

2019-11-05 21:25 UTC, CosmoMyzrailGorynych commented
> Should I also update the CHANGELOG.md?
No, it is semi-automatically-generated from the `git log`

> What is the versioning scheme for catmods: CompleteRewrite . NewFeature . BugFix ?
Semver, meaning BreakingChanges . NewFeature . Bugfix. I often forget about versioning modules at all, though :sweat_smile: Could you bump ct.mouse version then?

2019-11-05 21:29 UTC, CosmoMyzrailGorynych requested changes
So, a version bump — and all is good

2019-11-06 09:26 UTC, Wend1go commented
Ok done.

2019-11-06 21:09 UTC, CosmoMyzrailGorynych approved these changes

2019-11-06 21:09 UTC, merged