Add an ability to put one room into another
ct-js/ct-js-old pull request #158
Opened 2019-12-04 22:08 UTC by leedigital

Add an ability to put one room into another

2019-12-09 03:23 UTC, CosmoMyzrailGorynych requested changes
Well, it could be worse :/
I'll push my edits soon so that this resolves quicker and without possible misunderstanding.

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> + /*eslint complexity: ["error", 21]*/
=-= that ain't good

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            // eslint-disable-next-line no-underscore-dangle
Rules are rules; don't disable them freely everywhere

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +        },
All this looks overcomplicated, with extra methods and steps required neither for end-users (game developers) nor for those who will maintain it. `append` and `prepend` should be instant imo

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    }
Could be better written with a loop over ct.stage

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            this.rooms = [];
Memory leak: deleted copies/rooms don't get freed. New copies/rooms are not added as well. Backgrounds and tilesets are more static in this way; for copies, we already have `ct.types.list[...]`. Though there are `ct.types.list.BACKGROUND` and `ct.types.list.TILELAYER`.

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            // and these all are added to the current room, ct.room
Docs are good but could be better. See reference on additional tags of JSDoc syntax: https://jsdoc.app/

Adding `@param` flags and `@returns` provide hints for code editors like VSCode and are necessary for proper autocompletion inside ct.IDE.

2019-12-09 03:23 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            this.copies = [];
[`this.children`](http://pixijs.download/release/docs/PIXI.Container.html#children)?

2019-12-09 03:26 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            // eslint-disable-next-line no-underscore-dangle
In ct.js, I discourage the use of semi-private properties, and especially the use of such prefixes. An exception: `copy._deleted` is skipped in main.js, but because it is a built-in Pixi.js parameter.

2019-12-09 04:25 UTC, leedigital commented on app/data/ct.release/rooms.js
> +        },
So should it be attached when the room is attached / loaded to the view?

2019-12-09 04:30 UTC, leedigital commented on app/data/ct.release/main.js
> +    }
a loop over all children added to the stage and checking if it's an instance of Room?

2019-12-09 04:35 UTC, leedigital commented on app/data/ct.release/rooms.js
> +            this.rooms = [];
I thought about using ct.types.list ... but does it contain copies of all rooms or just the current room?

2019-12-09 04:36 UTC, leedigital commented on app/data/ct.release/rooms.js
> +            // and these all are added to the current room, ct.room
my mistake, sorry.

2019-12-09 04:38 UTC, leedigital commented on app/data/ct.release/rooms.js
> +            this.copies = [];
my mistake again... sorry.

2019-12-09 04:40 UTC, leedigital commented on app/data/ct.release/rooms.js
> +            // eslint-disable-next-line no-underscore-dangle
okay.

2019-12-09 05:38 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            this.rooms = [];
It contains all the not-killed copies. It is filled by `ct.types.make` (alias `ct.types.copy`), so nothing slips out of `ct.types.list`: https://github.com/ct-js/ct-js/blob/develop/app/data/ct.release/types.js#L348

2019-12-09 05:39 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    }
Yea
I pushed a commit that does just this
Though it still remains overcomplicated (cyclomatic complexity of 22, needs to be splitted)

2019-12-09 05:41 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +        },
I suppose that `ct.rooms.append/prepend` will be used not just in the OnCreate of a room, but also during runtime (think of a Minecraft-ish, chunk-based procedural world generation). In this case, `ct.rooms.prepend/append` should have an instant effect

2019-12-09 05:45 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +            this.copies = [];
One does not become a pro-coder in a day ¯\_(ツ)_/¯ There're indeed tons of stuff to note when developing such apps. And I need to write a style guide for code :eyes: 
Cheer up, it's always nice to see you contributing to ct.js ^-^

2019-12-09 06:01 UTC, leedigital commented on app/data/ct.release/main.js
> +    }
I saw it...

2019-12-10 01:05 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +<<<<<<< HEAD
How did it splip through??

2019-12-10 01:16 UTC, leedigital commented on app/data/ct.release/rooms.js
> +<<<<<<< HEAD
I am fetching and merging your last change ... I will make the adjustments and push again.

2019-12-10 01:30 UTC, leedigital commented on app/data/ct.release/rooms.js
> +<<<<<<< HEAD
done.

2019-12-10 02:58 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/rooms.js
> +     * @returns {Array<Copy|Background|Tileset>} An array of created copies, backgrounds, tile layers,
I made an incorrect typing here, silly me

2019-12-10 08:41 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> + /*eslint complexity: ["error", 21]*/
I pulled camera management code out of ct.loop and it all looks clean and pretty now.

2019-12-10 09:46 UTC, CosmoMyzrailGorynych commented
A little test suite: [multiRoomTest.zip](https://github.com/ct-js/ct-js/files/3944112/multiRoomTest.zip)

2020-02-16 10:06 UTC, CosmoMyzrailGorynych commented
[MouseAndTouchTest.zip](https://github.com/ct-js/ct-js/files/4209620/MouseAndTouchTest.zip)

2020-02-16 10:07 UTC, CosmoMyzrailGorynych approved these changes

2020-02-16 10:07 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +    const manageCamera = () => {
Affects one room only. Seems that it is a good time to introduce a concept of a camera

2020-02-16 10:22 UTC, CosmoMyzrailGorynych commented
Manually squash-merged in https://github.com/ct-js/ct-js/commit/902c92d1376427094afaecbb7736ceacf3eaae22

2020-02-16 10:22 UTC, closed without merging