:construction: Update german translation
ct-js/ct-js-old pull request #172
Opened 2020-02-25 13:37 UTC by Wend1go

**Changes proposed in this pull request:**
- Add German translation for particle effects
- Add some missing translation strings

**Note:**
This is a WIP. Please don't merge this yet since I wasn't able to check in the IDE if the translated strings are appropriate due to #171

2020-02-25 22:45 UTC, CosmoMyzrailGorynych commented
#171 is fixed, awaiting your review :+1:

2020-02-25 22:50 UTC, CosmoMyzrailGorynych commented
This range is not needed now and should be deleted; it is now replaced by `debuggerToolbar` namespace:
https://github.com/ct-js/ct-js/blob/33eb4ba18e20850bb74b66c3fb39d77bc6aa145d/app/data/i18n/German.json#L515-L521

2020-02-25 22:52 UTC, CosmoMyzrailGorynych requested changes

2020-02-25 22:52 UTC, CosmoMyzrailGorynych commented on app/data/i18n/German.json
> +        "flipLayout": "Debugger Layout ändern"
The namespace `preview` is not needed now and should be deleted; it is now replaced by `debuggerToolbar` namespace.

2020-02-25 23:09 UTC, CosmoMyzrailGorynych commented on app/data/i18n/German.json
> +        "flipLayout": "Debugger Layout ändern"
Oh, they're in English.json as well. Whoopsie!

2020-02-26 00:37 UTC, CosmoMyzrailGorynych commented on app/data/i18n/German.json
> +        "flipLayout": "Debugger Layout ändern"
So I wrote an i18n linter and cleaned excess fields in all language files. A merge from `develop` to your branch — and it is resolved.

2020-02-26 09:29 UTC, Wend1go commented
Ok, ready to merge. 😃

2020-02-26 21:02 UTC, CosmoMyzrailGorynych approved these changes

2020-02-26 21:03 UTC, merged