:construction: Issue 151: ct.flow, ct.u.wait, ct.tween should operate based on ct.delta, with optional setTimeout mode
ct-js/ct-js-old pull request #179
Opened 2020-04-06 17:27 UTC by naturecodevoid

Closes #151 .

**Changes proposed in this pull request:**

- ct.u.wait can use ct.delta, ct.deltaUi, or setTimeout
- Other methods can use ct.delta, ct.deltaUi, or setTimeout

2020-04-06 17:27 UTC, naturecodevoid commented
Sorry about the touch controls things, I was a little messy starting off.

2020-04-09 19:06 UTC, naturecodevoid commented
There's a really weird bug in the new system where if you start the test, it will never say done but if you reload or restart the room it will say done.

2020-04-11 02:24 UTC, CosmoMyzrailGorynych commented
Link https://github.com/ct-js/docs.ctjs.rocks/issues/2

2020-04-12 00:20 UTC, naturecodevoid commented
> Link [ct-js/docs.ctjs.rocks#2](https://github.com/ct-js/docs.ctjs.rocks/issues/2)

2020-04-12 00:20 UTC, naturecodevoid commented
oops

2020-04-12 00:21 UTC, naturecodevoid commented
oops sorry, accidentally clicked close and comment

2020-04-13 00:02 UTC, naturecodevoid commented
Sorry about all the commits and `.gitignore` becoming weird, had a lot of trouble merging but I believe I fixed it.

2020-04-15 05:15 UTC, CosmoMyzrailGorynych requested changes

2020-04-15 05:15 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +/* eslint-disable no-underscore-dangle */
Rules are made on purpose. Don't violate them.

2020-04-15 05:15 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +     * @param {boolean} [options.useTimeout=false] If true, use setTimeout() instead of ct.delta
I see no use in setTimeout method if there is an option to use `ct.deltaUi` instead of `ct.delta`. Let's remove this option and simplify the module.

2020-04-15 05:15 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +            }, 1 / 60);
There is a pretty bad thing about setInterval/setTimeout — here and in the current ct.js' state. Such intervals are running outside the `PIXI.Ticker`'s loop the whole game is using, and there will be inconsistencies in some edge cases, or when you rely heavily on a number of timers that run in parallel but are expected to trigger at one frame (and sometimes they won't as browsers are really bad at timings). 

Instead, it is better to use a class closer to classic ct.js timers described in tutorials — objects that have a numerical value that gets subtracted at each frame. Everything will then be dependent on one interval that PIXI and ct.js use. A boilerplate:

```js
class CtTimer {
  constructor(timeMs) {
    this.timeLeft = timeMs / 1000 * ct.speed;
    this.promise = new Promise((resolve, reject) => {
      this.resolve = resolve; // here we re-link resolve/reject callbacks so we can call them from anywhere
      this.reject = reject;
    });
    ct.timer.timers.push(this); // some array to loop over later
  }
}
// later, inside a timer's update function:
if (this.timeLeft <= 0) {
  this.resolve();
}
```

~~You can loop over all the timers at each frame by [using injections](https://docs.ctjs.rocks/making-mods.html#adding-injections) (`beforeroomstep.js` looks like a good candidate).~~ 🤦 Forgot that it is not a module but basic ct.js functionality

This all will also shrink your code. Less code = fewer bugs =  less stuff to maintain 👍

2020-04-15 05:15 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/main.js
> +                    if (ct.timer._timersInternal["ct.u.wait"] / 60 * 1000 >= time) {
Let's use `ct.speed` instead of `60`. `ct.speed` is bugged on lower FPS set in a project's settings, tho, but I'll fix it soon :D

2020-04-15 05:15 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/timer.js
> +/* eslint-disable no-underscore-dangle */
Violation 🚓 (wew-wew-wew)
You can create JS Symbols for private variables. Basically you `const timeSymbol = new Symbol('ct.timer\'s time variable')` and then use `this[timeSymbol]` to read/write to it. The string passed to the constructor is just a descriptive label shown in console. Symbols are better than just undocumented vars as they don't appear in the console while typing, though still can be seen if you console.log the whole `this` object.

2020-04-15 05:15 UTC, CosmoMyzrailGorynych commented on app/data/ct.release/timer.js
> +        addTimedTimer(name, length, callback, uiDelta = false, startTime = 0) {
What's the difference to the regular timers??

2020-04-15 05:16 UTC, CosmoMyzrailGorynych commented
I somehow forgot to send these comments, sorry for the delay D:

2020-04-15 13:20 UTC, naturecodevoid commented on app/data/ct.release/timer.js
> +        addTimedTimer(name, length, callback, uiDelta = false, startTime = 0) {
CtTimedTimer runs a function when it gets to a certain point but is slightly bugged

2020-04-15 21:25 UTC, naturecodevoid commented
Changes to be made based on your feedback:

- [ ] Use symbols for "private" variables
- [ ] Use a promise for simplified timers
- [ ] Don't violate Eslint rules
- [ ] Simpler timers
- [ ] `ct.speed` 
- [ ] No `setTimeout` mode

2020-04-21 18:41 UTC, naturecodevoid commented
Everything should be ready to go soon now that I have finished everything except the documentation.

2020-04-22 01:50 UTC, CosmoMyzrailGorynych commented
I need to fix ct.IDE first so I can test all it out x_x

2020-04-30 22:29 UTC, CosmoMyzrailGorynych commented
A couple of things I'll add/change:

* [ ] An ability to re-run a timer so its `then` can be called numerous times.
* [ ] Split `ct.u.wait` into `ct.u.wait` and `ct.u.waitUi`, for verbosity and to comply with existing API.
* [ ] Make `name` visible so it can be used by developers (e.g. while using one function for numerous timers)
* [ ] Store timers in an array so you can have timers with the same name (think of dozens of enemies that all use `debuff` and `shoot` timers) 
* [ ] `ct.timer.removeTimer(name);` -> `timer.remove();`

2020-05-04 08:54 UTC, merged