Discord rpc fixes
ct-js/ct-js-old pull request #243
Opened 2020-10-23 16:33 UTC by naturecodevoid

**Changes proposed in this pull request:**

- Major improvements + bug fixes for discord rpc

2020-10-25 11:35 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +    }, 1000 * 5);
Update rate limit is 15 seconds

2020-10-25 14:08 UTC, naturecodevoid commented on src/js/discordRichPresence.js
> +    }, 1000 * 5);
really? I didn't have a problem using this or 1 second, iirc

2020-10-25 21:55 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +    }, 1000 * 5);
https://discord.com/developers/docs/rich-presence/how-to#updating-presence

> Discord_UpdatePresence() has a rate limit of one update per 15 seconds

2020-10-25 22:04 UTC, CosmoMyzrailGorynych requested changes

2020-10-25 22:04 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +    };
Superflous; no one will care about Discord rich presence. And no reason to spam messages if they don't have Discord at all.

2020-10-25 22:04 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +        setTimeout(() => changeDiscordStatus(document.querySelector('main-menu')._tag.tab), 250);
Please don't do that (querying tags and going into `_tag` properties). Instead, call this.changeTab in main-menu tag, so nothing breaks if a tag gets renamed or its functionality changes.

2020-10-25 22:04 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +            changeDiscordStatus(document.querySelector('main-menu')._tag.tab);
Again, querying + `_tag`.

2020-10-25 22:04 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +            largeImageText: 'ct.js (https://ctjs.rocks/)',
Spamming links in foreign people's RP is beyond ugly.

2020-10-26 05:45 UTC, yonderbread commented on src/js/discordRichPresence.js
> +            largeImageText: 'ct.js (https://ctjs.rocks/)',
agreed, if you're gonna put links there maybe make one of the status texts a hyper link

2020-10-30 18:25 UTC, naturecodevoid commented on src/js/discordRichPresence.js
> +    };
I don't see why not to give a warning

2020-10-30 18:25 UTC, naturecodevoid commented on src/js/discordRichPresence.js
> +    }, 1000 * 5);
> Developers do not need to do anything to handle this rate limit

2020-10-31 02:49 UTC, CosmoMyzrailGorynych commented on src/js/discordRichPresence.js
> +    }, 1000 * 5);
We don't use Discord's SDK, helloooo

2020-10-31 03:04 UTC, naturecodevoid commented on src/js/discordRichPresence.js
> +    }, 1000 * 5);
doesn’t really matter, there’s no problem when using 2 second delay

2020-11-02 05:53 UTC, CosmoMyzrailGorynych commented
Merged in https://github.com/ct-js/ct-js/commit/696130199e5bf159dde079994168b5fc15a7a491

2020-11-02 05:53 UTC, closed without merging