Example bug fixes
ct-js/ct-js-old pull request #288
Opened 2021-06-07 10:35 UTC by markmehere

Still really enjoying this @CosmoMyzrailGorynych!

Got some bigger ideas ahead - we'll see if they work. But for now just some bug fixes for the examples.

Specifically:

* `ct.types.move(this)` to `this.move()` or deleted
* `ct.viewWidth` to `ct.width`
* `sound.howler: {}` added where required

As well as two other changes:

* `npm start` to run `gulp` for those of us not used to `gulp`
* `ct.libs/touch`'s `mouseUp()` to use `.filter(x => x.id !== -1)` to release all mouse events thus preventing a bug when the user's mouse is released but the browser is not informed. Previously this was irrecoverable because an additional mouse press/release would only create and then release the same single event. Now with a mouse press/release cycle releasing all events it becomes the recovery mechanism.

The attached video shows the issue. Mouse button is pressed then released outside the browser window creating the issue. And then repeated click/releases are made inside the browser window to attempt recovery. No recovery is possible in the buggy version (shown), recovery is possible with the `.filter(x => x.id !== -1)` fix.

https://user-images.githubusercontent.com/52765023/121002428-ac6e4e80-c7cf-11eb-8980-10d7f97ff792.mp4

2021-06-07 21:48 UTC, CosmoMyzrailGorynych requested changes
Two tiny edits are recommended.

2021-06-07 21:48 UTC, CosmoMyzrailGorynych commented on src/examples/SpaceShooter_tutorial.ict
> +          ct.types.copy(ct.random.dice('Asteroid_Big', 'Asteroid_Medium'), ct.random(ct.width), -100);
`ct.width` and `ct.height` are better replaced with `ct.camera.width` and `ct.camera.height`. `ct.width` and `ct.height` differ from those under various fittoscreen modes.

A more proper way that takes into account camera scaling (absent in this example) is to use `ct.camera.getBoundingBox().width` and `.height`.

2021-06-07 21:48 UTC, CosmoMyzrailGorynych commented on src/examples/SpaceShooter_tutorial.ict
> +          ct.types.copy('EnemyShip', ct.random(ct.width), -100);
Same as above.

2021-06-09 04:46 UTC, markmehere commented
Done with changes @CosmoMyzrailGorynych

2021-06-11 02:22 UTC, CosmoMyzrailGorynych approved these changes

2021-06-11 02:23 UTC, merged