:zap: Do not minify HTML/CSS when not minifying JavaScript
ct-js/ct-js-old pull request #364
Opened 2022-09-11 06:39 UTC by markmehere

I haven't actually minified any of my released Ct.js projects, but I noticed Ct.js minfies the HTML/CSS regardless.

This PR disables minification of the HTML/CSS when the user has elected not to minify JavaScript.

There are a bunch of reasons the user may want to review the HTML/CSS including to source Pixi.js from a CDN*, to see where their custom HTML/CSS has been inserted, etc.

_* Potentially CDN-sourced Pixi.js should be an export setting as it's something the user will want repeatedly. But for now I still feel this PR is a positive addition._

2022-09-11 07:11 UTC, CosmoMyzrailGorynych commented
Better split this behavior into two/three options and leave HTML+CSS minification on by default. The reasons not to minify CSS and HTML are quite rare, as you can inspect them without specific tools anyways (e.g. any browser debugger shows everything neatly arranged for you regardless of internal formatting).

2022-09-11 07:12 UTC, CosmoMyzrailGorynych commented
> * Potentially CDN-sourced Pixi.js should be an export setting as it's something the user will want repeatedly.

We definitely talk about different target audiences here 🙃

2022-09-11 07:14 UTC, CosmoMyzrailGorynych requested changes
Need additional project settings for that

2022-09-13 09:22 UTC, markmehere commented
I can add a checkbox. _But is that your final answer?_ 🙂

In addition to needing translation, the problem is developers can overwhelm users with project settings.

Not minifying HTML/CSS:

* only cost an extra four dozen characters
* gives beginners clear visibility of how their game is just a "index.html" web page like they may have seen elsewhere
* seems logical when the JavaScript is not minfied

I guess the advantage of the checkbox is those cases where users want visibility of the HTML web page but also minified JavaScript code (which can halve in size with minification).

2022-09-14 07:22 UTC, CosmoMyzrailGorynych commented
Ok, you got your point.
Let me update JSONBabel so we can track outdated translations, and I'll merge it.

2022-10-24 07:20 UTC, CosmoMyzrailGorynych approved these changes
Ok, it took longer than I anticipated due to, well, life.
Merging it as is.

2022-10-24 07:21 UTC, merged