:sparkles: Adds TypeScript support
ct-js/ct-js-old pull request #369
Opened 2022-09-13 09:07 UTC by markmehere

This relatively simple PR enables TypeScript support for game development. I thought this was a request but can't find the related issue.

There are four parts to it:

1. It adds [sucrase](https://github.com/alangpierce/sucrase) to remove the TypeScript from exports.
2. It converts the script editor to `typescript`
3. It removes the script's typings upon load instead of if there has been a rename
4. It names scripts sequentially "New Script", "New Script 1", "New Script 2", etc.

Explaining each...

1. [sucrase](https://github.com/alangpierce/sucrase) is a fast light-weight cross-compiler. It does TypeScript to ES6, JSX to ES6 and a few others. I was so impressed by the speed, that I removed an initial disable TypeScript option. TypeScript removal happens before the minification as many minifiers require.
2. Making the script editor TypeScript picks up a huge number of additional errors for example `const x = 6; console.log(x.hello)` is valid JavaScript code even though it makes no sense. I suspect the reason why the script editor was made JavaScript is because the editor kept complaining about duplicate function/variable names.
3. The editor kept complaining about duplicate function/variable names because the script being edited was also a library. So Monaco would see `function helloWorld() { ... }` in "New Script 5" and say I already have that function you added it as part of "New Script 5". Removing the "New Script 5" typings on first load of that script in the script editor prevents duplicate complaints - the only downside is the (hopefully brief) moment without typings if users switch to the room editor without first saving their script.
4. The code correctly checks if there exists typings for the script it is loading and only removes them if there does. In the case of "New Script" there are none and Ct.js proceeds normally. But if the user had saved a previous script as "New Script" those typings would be removed upon creation of a new "New Script". Thus uniquely named scripts become more important. This doesn't fix users deliberately naming everything "My Script" and destroying their typings, but it does start them on the right footing by making sure each newly created script has a unique name.

I thought about adding a new example showing off the new features but I'm not sure it's necessary now.

2022-09-13 11:23 UTC, CosmoMyzrailGorynych requested changes
I'm mostly positive about this PR, though it is more fake than real support for TypeScript than a real one. But adding real support would be a terrible mess as well.

Perhaps later ct.js will do a sweep on all the events and scripts and utilize the typescript engine bundled with monaco to report issues at exports, similar to how VSCode does it.

With minor issues fixed (var -> const/let), I'll be ready to merge the PR.

2022-09-13 11:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/project-settings/tabs/scripts-setttings.tag
> +            var oldScriptNames = this.currentProject.scripts.map(script => script.name);
Must be `const` for `oldScriptNames`, `newName`, `script`. This is an arrow function, you are leaking variables into the tag's function.

2022-09-13 11:23 UTC, CosmoMyzrailGorynych commented on src/riotTags/project-settings/tabs/script-editor.tag
>                  var editorOptions = {
oh no, I wrote a `var` one day, too

2022-09-14 01:49 UTC, markmehere commented on src/riotTags/project-settings/tabs/script-editor.tag
>                  var editorOptions = {
Yeah I could never figure out the `var`/`const`/`let` thing in this project - I'm always using `const`/`let` in my own projects. I must admit I never took the time to fully understand why you wouldn't.

2022-09-14 01:59 UTC, markmehere commented on src/riotTags/project-settings/tabs/script-editor.tag
>                  var editorOptions = {
One other question I have, in the codebase, from what I'm seeing we started out with ES6 but are slowly migrated across to TypeScript. So if I do any work and it's convenient/appropriate, I should feel free to make the new code in TypeScript?

2022-09-14 06:33 UTC, CosmoMyzrailGorynych commented on src/riotTags/project-settings/tabs/script-editor.tag
>                  var editorOptions = {
Yes, it is better to use TS where possible.
About `var` and JS in general — ct.js had started its existence when neither typescript nor ES6 did. And I code on JS since, like, 7 years? (2003???) and don't understand why people find problems in the things that were fundamental for dozen and a half years (`var` and closures, and prototyping)

2022-09-14 06:34 UTC, CosmoMyzrailGorynych commented on src/riotTags/project-settings/tabs/script-editor.tag
>                  var editorOptions = {
Of course, it is not people finding problems in `var` — the problem is in people that misuse it.

2022-09-14 06:36 UTC, CosmoMyzrailGorynych commented on src/riotTags/project-settings/tabs/script-editor.tag
>                  var editorOptions = {
I believe there is enough code that was migrated when ct.js was based on jQuery (when there was no React/Angular/riot.js)

2022-09-14 06:36 UTC, CosmoMyzrailGorynych approved these changes

2022-09-14 06:37 UTC, merged