:sparkles: Allow multiple projects open at once
ct-js/ct-js-old pull request #378
Opened 2022-10-01 14:26 UTC by markmehere

I think this is almost ready-to-go but I'll keep a draft tag on it for a short while.

This allows multiple projects to be open at the same time (useful for transferring code).

Nothing fancy like a working Window menu yet.

Ct.js was almost ready-to-go for this change due to its good use of sessionStorage vs. localStorage.

The feature is a light-touch retaining the existing open functionality everywhere but adding a single button "Start new window" in the project menu.

In addition:

* Code is added to check the same project is not opened several times (could spell trouble)
* Code is added to ensure the global notepad is updated during switches

2022-10-02 01:51 UTC, FlipFloop commented
I think another way of doing this would be able to generate a `./common` folder. So we can simply have that on the filesystem, add sprites, movements scripts, sounds etc. and just choose whether to import from common? Almost like a template?

2022-10-02 02:00 UTC, FlipFloop commented
Also, can't work on this as M1 not enabled :(

2022-10-02 02:12 UTC, markmehere commented
@FlipFloop Yes until the Apple silicon builds are merged - none of the branches are going to run natively on your computer. 🤔 You have to pull both changes into a single branch.

2022-10-02 03:27 UTC, CosmoMyzrailGorynych commented
Wow @markmehere, you were busy these two weeks! I returned from my business trip just yesterday and will need time to merge all this :eyes:

2022-10-02 03:35 UTC, CosmoMyzrailGorynych commented on src/riotTags/main-menu/main-menu-project.tag
> +                title: 'ctjs'
These all can be replaced with `require('./package.json').window`

2022-10-02 03:36 UTC, CosmoMyzrailGorynych commented on src/riotTags/main-menu/main-menu-project.tag
> +                title: 'ctjs'
`min_width` and `min_height` are incorrect; when needed, on tiny screens, ct.js can be zoomed out.

2022-10-02 03:37 UTC, CosmoMyzrailGorynych requested changes
Window creation should follow what is in package.json of the app.

2022-10-02 03:53 UTC, markmehere commented on src/riotTags/main-menu/main-menu-project.tag
> +                title: 'ctjs'
Mac OS X defaults to these minimum values at random times. This is a nw.js issue. But rest sounds good to me.

2022-10-02 21:51 UTC, FlipFloop commented
> I think another way of doing this would be able to generate a `./common` folder. So we can simply have that on the filesystem, add sprites, movements scripts, sounds etc. and just choose whether to import from common? Almost like a template?

Is this idea dumb? I think it'd save time from copying stuff over and over.

2022-10-02 22:48 UTC, CosmoMyzrailGorynych commented
> Is this idea dumb?

It's as raw as a living chicken. Too broad, too vague, and not relying on existing functionality.

2022-10-02 23:32 UTC, FlipFloop commented
> > Is this idea dumb?
> 
> It's as raw as a living chicken. Too broad, too vague, and not relying on existing functionality.

Solid. I'll **cook** it for us all then.

2022-10-04 00:48 UTC, markmehere commented
@FlipFloop I like the idea of a game component library and I think it's not the first time it's been raised.

Though my PRs seem all over the place, almost all are based on issues I'm encountering while making games.

So this feature is simply because I need to bring data across from one project to another. Doing it without the multi-windows is painful.

This is not, for example, a solution for https://github.com/ct-js/ct-js/issues/48 - which is slightly different.

A component library for ct.js game developers (so you can drag in a timer or quit button or flying cat sprite) can be easy to do badly. So the trick is to get a really crisp implementation that's as simple as possible.

I'm sort of thinking of an online GitHub repository that can inject code and assets anywhere in the ct.js project. The GitHub would make it a walled garden. The idea is once you imported that flying cat from the online repository it would become like any other asset in your project. You could modify it however you want.

In terms of priority, I probably would like to see drag-n-drop text sprites first. It just seems like a really big gap at the moment.

2022-10-04 00:50 UTC, markmehere commented
This is still in draft, btw, because without a proper Windows menu - the multi-window on Mac OS X feels really strange. Apple causing trouble again. 🤬

2022-10-04 00:52 UTC, markmehere commented
Every other pull request though is good to go. #372 👀 for example. This is, IMHO, important for OS X.

2022-10-04 03:49 UTC, CosmoMyzrailGorynych commented
@markmehere https://github.com/ct-js/ct-js/issues/203 wink-wink template behaviors wink-wink

2022-10-04 03:54 UTC, CosmoMyzrailGorynych commented
> This is still in draft, btw, because without a proper Windows menu - the multi-window on Mac OS X feels really strange. Apple causing trouble again. 🤬

AFAIK the Window menu can be replaced with nw.js API: https://nwjs.readthedocs.io/en/latest/References/Menu/#menucreatemacbuiltinappname-options-mac

2022-10-23 09:46 UTC, markmehere commented
> AFAIK the Window menu can be replaced with nw.js API: https://nwjs.readthedocs.io/en/latest/References/Menu/#menucreatemacbuiltinappname-options-mac

This sounds good and I spotted it too - but actually isn't anywhere near as useful as it could be and (for document management) the heavy lifting is left entirely to the app.

2022-10-24 07:52 UTC, CosmoMyzrailGorynych commented on src/js/utils/windowMenuHelper.js
> +        resolve(windows.map(win => {
Cool! Now I vaguely know what it is all about! 😅

2022-10-24 07:53 UTC, CosmoMyzrailGorynych approved these changes

2022-10-24 08:24 UTC, merged