:sparkles: Catmot Game Distribution
ct-js/ct-js-old pull request #394
Opened 2022-11-05 10:45 UTC by UlisesFreitas

- [x] `gulp build` runs without issues.
- [x] if you develop a catmod, a test project and docs are also present. Put a test project into a catmod's directory.
- [ ] if it is a work-in-progress, explicitly mark it as such in the title with the `WIP: ` prefix.
- [x] The title of the pull request has a suitable emoji from [the Comigoji guide](https://comigo.gitlab.io/comigoji/#gitmoji). The title *will* look broken on GitHub, but it streamlines further merging and makes writing a pretty changelog easier.

**Changes proposed in this pull request:**

Add a new catmod for the useers to use the Game Distribution SDK to display Ads in their games.
- Added a new Catmod for Game Distribution Ads in the ct.libs - 
-  Added a new Example in the Examples folder

**Ping @CosmoMyzrailGorynych**

2022-11-06 09:33 UTC, CosmoMyzrailGorynych requested changes
_Well,_
There is misleading stuff here and there, typos, and just improper newbie JS code that must not be taught to others. And ideally — not used in code, too.

General advice: use either "Ad" or "Banner", not both.
One event is useless.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +* Install or enable `ct.pointer` and add `On click` event to your button template.
Despite common sense, `ct.pointer` is not required for built-in pointer events.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/events/pausegame_thisOnStep.js
> +    if(ct.gamedistribution.isPaused == false){
bruuuuh, that code smells, and smells bad.

`if(ct.gamedistribution.isPaused == false){` is the same as `if(!ct.gamedistribution.isPaused) {`

Comparing with `true` or `false` is superflous.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/events/resumegame_thisOnStep.js
> +        if (ct.gamedistribution.adPlaying == false) {
same issues

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/events/showadonclick_thisOnStep.js
> +            if (ct.gamedistribution.adPlaying == false) {
Comparing with `false` again

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/events/showadonclick_thisOnStep.js
> +        const other = ct.templates.list[[/*%%template%%*/]][0];
This line is broken and gives 0 sense.

In syntax sense, it should be `ct.templates.list[/*%%template%%*/][0];`.

In logical sense, you pick a first copy of a specific template, and test against it, when it can be a wrong copy if you have several of them.

All in all, this event is useless as it does not use code written in this event (`/*%%USER_CODE%%*/` is absent).

What should be done instead of adding this broken event is telling users to run this on vanilla "On click" events:
```js
if (!ct.gamedistribution.adPlaying) {
    ct.gamedistribution.showBanner();
}
```
That's all. No use of ct.pointer or whatever is required.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/index.js
> +						0
What the heck is this

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/index.js
> +					gdsdk.showAd();
You need to settle on either "Ad" or "Banner", mixing them is confusing.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "help": "Enable to track cookies",
This is better to be elaborated. Writing a fancy abbreviation doesn't tell whether you are doing anything right or still have to care about regulations.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +        },
This is not how ct.js events are supposed to work. This is to be removed.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "parameterizedName": "Check if an Ad is finished.",
Why do these differ? Why do you use a parametrized name when you don't have parameters for this event?

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "name": "Ad is finished",
Ad is finished -> Ad **has** finished

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "hint": "Use this to reward the user, maybe with coins, gold or crystals.",
Use this to reward the user, maybe with coins, gold or crystals.
|
v
Happens right after an ad has finished and closed. Use this to reward the user, maybe with coins, gold or crystals.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "parameterizedName": "Check if the Game Distribution SDK is ready.",
Again, useless name.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "parameterizedName": "You must pause the game and mute sfx and music.",
Useless name

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "name": "Pause Game",
Pause game -> "Ad started", I guess?

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/module.json
> +            "name": "Resume Game",
Resume game -> "Ad closed", I suppose?

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +I case you need to manually resume the game do:
I case -> In case

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +  if (ct.gamedistribution.adPlaying == false) {
use of `== true` and `== false` again

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +        if (ct.gamedistribution.adPlaying == true) {
use of == true and == false again

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +- [Event][Type][thisOnStep] Show Ad
This is confusing. A user does not need to know how your events work. Just write names of events only.

2022-11-06 09:33 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +`ct.gamedistribution.ShowBanner();`
`ShowBanner` -> `showBanner` (a typo)
And `showAd` is better.

2022-11-10 07:39 UTC, CosmoMyzrailGorynych reviewed
Added 3 new comments. Awaiting for previous fixes, too.

2022-11-10 07:39 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/docs/General use.md
> +if (ct.gamedistribution.adPlaying) {
isn't it `if (!ct.gamedistribution.adPlaying) {`?

2022-11-10 07:39 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/gamedistribution/index.js
> +						0
I don't think this method should change the value `ct.gamedistribution.isFinished`. It is counterintuitive.

2022-11-10 07:39 UTC, CosmoMyzrailGorynych commented on app/data/ct.libs/ulid/module.json
> +{
It would be better if this module was in another PR. I can still merge it if it is not a mistake.

2022-11-10 12:52 UTC, UlisesFreitas commented on app/data/ct.libs/ulid/module.json
> +{
Sure I messed up with the pull request the ct.ulid it's a different Catmod, not related at all with the GameDistribution, sorry for that, just let me finish with the GD, then I'm going to create another pull for the ct.ulid.

2022-11-18 09:13 UTC, CosmoMyzrailGorynych approved these changes

2022-11-18 09:14 UTC, CosmoMyzrailGorynych commented
@UlisesFreitas should I merge ct.ulid with this, or wait for you to remove it from this PR?

2022-11-18 10:53 UTC, UlisesFreitas commented
Hi sure merge ct.ulid from here, in the future I'll make sure to just push catmods in differents PR. 
Thanks.

2022-11-21 07:40 UTC, merged