Update Japanese translation
ct-js/ct-js-old pull request #404
Opened 2023-01-05 13:33 UTC by taxi13245

**Changes proposed in this pull request:**

-Fixed a syntax error in the Json file.
-Added missing Japanese translation.
-Corrected some spelling inconsistency.

**Ping @CosmoMyzrailGorynych**

2023-01-06 17:18 UTC, CosmoMyzrailGorynych requested changes
```

Translation file Japanese.json
------------------------------
Coverage: 95% 💙  Fabulous!
Not translated: 26
  colorPicker.altClick
  exporterError
  intro.sponsoredBy
  intro.supportedBy
  languageSelector
  patreon.sponsors
  patreon.noSponsorsYet
  patreon.sponsorsDescription
  patreon.businessCats
  patreon.businessCatsDescription
  patreon.cats
  patreon.catsDescription
  mainMenu.settings.altTemplateLayout
  mainMenu.project.startNewWindow
  mainMenu.project.convertToJs
  mainMenu.project.confirmationConvertToJs
  roomTiles.addTileLayer
  roomTiles.addTileLayerFirst
  roomView.viewportHeading
  roomView.followTemplate
  roomView.followCodeHint
  textureView.slicing
  textureView.viewSettings
  textureView.exportSettings
  textureView.axisExplanation
  scriptables.jumpToProblem
Excess: 11 ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
  patreon.businessShuttles
  patreon.noShuttlesYet
  patreon.shuttlesDescription
  patreon.spacePirates
  patreon.noPiratesYet
  patreon.piratesDescription
  patreon.spaceProgrammers
  patreon.programmersDescription
  patreon.aspiringAstronauts
  patreon.noAstronautsYet
  patreon.astronautsDescription
```

2023-01-06 17:18 UTC, CosmoMyzrailGorynych commented on app/data/i18n/Japanese.json
> +        "astronautsDescription": "宇宙飛行士はDiscordで特別な役割を与えられ、ここにリストアップされます。",
These are outdated and must not be in new releases. Having these keys will break the build.

2023-01-07 14:28 UTC, taxi13245 commented on app/data/i18n/Japanese.json
> +        "astronautsDescription": "宇宙飛行士はDiscordで特別な役割を与えられ、ここにリストアップされます。",
Thanks for the reply. How do I send the changes, do I just recreate the PullRequest again?

2023-01-07 14:46 UTC, taxi13245 commented on app/data/i18n/Japanese.json
> +        "astronautsDescription": "宇宙飛行士はDiscordで特別な役割を与えられ、ここにリストアップされます。",
Thanks for the reply.
I have added a new commit.
Please check it out.

2023-01-08 11:17 UTC, CosmoMyzrailGorynych commented
I'll review it once I'm in an adequate work environment; I'm on a trip far from home rn. Sorry for the delays!

2023-02-24 03:51 UTC, CosmoMyzrailGorynych approved these changes
Looks good!

2023-02-24 03:51 UTC, merged