:zap: Exclude blank textures from export and retain shape
ct-js/ct-js-old pull request #433
Opened 2023-09-16 07:37 UTC by markmehere

I love my blank textures but unfortunately there were a few bugs in the first implementation. This pull request:

* Excludes the blank textures from export (part of the whole point of them)
* Retains the shape of the blank texture so it can be used as a button

`PIXI.Graphics` considers (0, 0) to be the anchor point of a blank texture. This is confusing **however** `PIXI.Graphics` considers (0, 0) to be the anchor point of a non-blank texture - so the behaviour is consistent.

This is another pull request in my attempts to cherry pick the easiest most mature fixes from [this branch](https://github.com/markmehere/ct-js/tree/various-fixes-updated) and generate pull requests for them.

2023-09-16 09:57 UTC, CosmoMyzrailGorynych requested changes

2023-09-16 09:57 UTC, CosmoMyzrailGorynych commented on src/node_requires/resources/templates/ITemplate.d.ts
> +    shape?: any,
This looks like an error

2023-09-16 09:58 UTC, CosmoMyzrailGorynych commented on src/node_requires/resources/templates/ITemplate.d.ts
> +    shape?: any,
I don't see you using shapes for templates exactly, and templates should not use shapes directly either way.

2023-09-16 23:27 UTC, markmehere commented on src/node_requires/resources/templates/ITemplate.d.ts
> +    shape?: any,
Good pick-up this has been removed.

2023-09-17 07:35 UTC, CosmoMyzrailGorynych approved these changes

2023-09-17 07:36 UTC, merged

2023-10-18 10:29 UTC, CosmoMyzrailGorynych commented
@markmehere I'm merging changes from `develop` to `pixi-v7` branch and I did not understand how and why you pull texture shape from a template <_> for now I will exclude this PR and the next one (about ct.splashscreen) from pixi-v7