:bug: Context menu fixes
ct-js/ct-js-old pull request #446
Opened 2023-10-24 11:27 UTC by markmehere

Three fixes to the `pixi-v7` branch:

* Rename fix for asset browser (a simple typo correction)
* Resolve `vocPath` to fix context labels (this is done using the existing `lodash` version)
* Restore set starting room menu item

`gulp lint` is reporting a heroic `74836 problems (74177 errors, 659 warnings)` so I wasn't able to lint it.

**Ping @CosmoMyzrailGorynych**

2023-10-24 11:32 UTC, CosmoMyzrailGorynych requested changes
> a heroic 74836 problems

Yeeeea

Could you make a separate PR/cleanup this one for starting room fix solely? I have fixes for vocPath and asset browser in uncommitted changes (and much more) already, and I don't like adding lodash for such a trivial task 🙈

I will start adding my fixes in several hours

2023-10-24 12:54 UTC, markmehere commented
The implementation of starting rooms isn't anything particularly special or even good...

```
const assetContextMenuItems: IAssetContextItem[] = [
    {
        icon: 'play',
        vocPath: 'rooms.makeStarting',
        action: async (
            asset: ISkeleton,
            collection: folderEntries,
            folder: IAssetFolder
        ) => {
            global.currentProject.startroom = asset.uid;
        }
    }
];
```

I'd just add it in to `src/node_requires/resources/rooms/index.ts`. I'm looking forward to seeing the other changes. In my testing, I found the `develop` branch easier to make games from. Though longer term the `pixi-v7` branch seems the way to go.

2023-10-25 07:31 UTC, CosmoMyzrailGorynych commented
> I'd just add it in to `src/node_requires/resources/rooms/index.ts`.

Added it to pixi-v7 and tagged you as an author.
With that, I think this branch can be closed. Thank you for your work!

> In my testing, I found the develop branch easier to make games from. Though longer term the pixi-v7 branch seems the way to go.

The `develop` branch is currently for v3.2 fixes only, with new features appearing in pixi-v7. Once the sound API update is in it and once emitter-tandem-editor is revived, it will be merged into `develop` so it comes out in ct.js nightly. With broken sounds and emitters, it is ofc not easy to make games in it :D
But I myself got used to folder+tabs layout pretty quickly; I try making a game in it and am writing fixes for any bugs I'm facing during it, and also I'm writing #445 bc the current game (and, well, all ct.js users) would benefit greatly from that addition, and ct.js v4 API and component set allows doing it with relative ease now.

2023-10-25 07:31 UTC, closed without merging

2023-10-25 07:37 UTC, CosmoMyzrailGorynych commented
If you're looking for work to do with ct.js, it would be cool if you fixed emitter-tandem-editor and subtags. (It's a mess, here be dragons, beware!)
I updated the ITandemEmitter format, added migration scripts, and the editor can open basic emitters now, but even if it does, changes are not real-time. [The pixi-particles package had heaps of breaking changes.](https://github.com/pixijs/particle-emitter#breaking-changes-in-v5-from-v4) And that whole ordeal gave me trauma and I would be happy if you spared me from dealing with this XD